name: Bug Report
description: Report a bug with the HullCSS Bot
title: '[BUG REPORT] <Concise description of the bug>'
labels: ['bug']

### Bug Description
_A clear and concise description of what the problem is_

### Expected Result
_A clear and concise description of what the expected result is_

### Actual Result
_A clear and concise description of what the actual result is_


